# Generated by Django 3.1.4 on 2020-12-08 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2021, 1, 8)),
        ),
    ]
